#!/bin/bash

curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
sudo mv /tmp/eksctl /usr/local/bin
Verify eksctl version : 
 eksctl  version 

 curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip awscliv2.zip
sudo ./aws/install
eksctl create cluster --name dev --version 1.21 --region us-east-1 --nodegroup-name liontechacademy --node-type t3.micro --nodes 3 --nodes-min 1 --nodes-max 4 --managed
