#!/bin/bash
#1) Create Ubuntu EC2 instance

#2) install AWSCLI

 sudo apt update -y
 sudo apt install awscli

#Install wget if not installed
  sudo apt install wget -y
  sudo wget https://github.com/kubernetes/kops/releases/download/v1.16.1/kops-linux-amd64
  sudo chmod +x kops-linux-amd64
  sudo mv kops-linux-amd64 /usr/local/bin/kops
 
#4) Install kubectl

 sudo curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
 sudo chmod +x ./kubectl
 sudo mv ./kubectl /usr/local/bin/kubectl




#Then Attach IAM role to ubuntu server from Console Select KOPS Server --> Actions --> Instance Settings --> Attach/Replace IAM Role --> Select the role which
#You Created. --> Save.
 # make a bucket: 
  aws s3 mb s3://k8s-liontech-k8s-bucket
  export KOPS_STATE_STORE=s3://k8s-liontech-k8s-bucket
 # create your cluster:
  kops create cluster --name liontech.k8s.local  --zones ca-central-1b --networking weave --master-size t2.large --master-count 1 --node-size t2.large --node-count=3 

#ssh-keygen: 
#export key to cluster: 
  kops create secret --name liontech.k8s.local sshpublickey admin -i ~/.ssh/id_rsa.pub
    
  #  create the cluster : 
 kops update cluster --name liontech.k8s.local --yes

    



#list clusters with: kops get cluster
 #* edit this cluster with: kops edit cluster liontech.k8s.local
 #* edit your node instance group: kops edit ig --name=liontech.k8s.local nodes
 #* edit your master instance group: kops edit ig --name=liontech.k8s.local master-ca-central-1b

#Finally configure your cluster with: 
kops update cluster --name liontech.k8s.local --yes